version: "3.8"
services:
  postgresdb:
    image: postgres
    container_name: e-learning-postgrest
    restart: always
    environment:
      POSTGRES_PASSWORD: SakataGintoki@123
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data