/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-04-23 10:39:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cybersoft.java09.dto.UserDto;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("cybersoft.java09.dto.UserDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
 String contextPath = request.getContextPath() ;
	UserDto userDto = (UserDto)request.getAttribute("userDto");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("window.onload = function () {\r\n");
      out.write("\r\n");
      out.write("var chart = new CanvasJS.Chart(\"chartContainer\", {\r\n");
      out.write("	theme: \"light1\", // \"light2\", \"dark1\", \"dark2\"\r\n");
      out.write("	animationEnabled: false, // change to true		\r\n");
      out.write("	title:{\r\n");
      out.write("		text: \"Work Status\"\r\n");
      out.write("	},\r\n");
      out.write("	data: [\r\n");
      out.write("	{\r\n");
      out.write("		// Change type to \"bar\", \"area\", \"spline\", \"pie\",etc.\r\n");
      out.write("		type: \"column\",\r\n");
      out.write("		dataPoints: [\r\n");
      out.write("			{ label: \"Chưa thực hiện\",  y: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDto.notDoneWorkPercent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("  },\r\n");
      out.write("			{ label: \"Đã thực hiện\", y: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDto.pendingWorkPercent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("  },\r\n");
      out.write("			{ label: \"Đã hoàn thành\", y: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDto.finishWorkPercent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" },\r\n");
      out.write("			\r\n");
      out.write("		]\r\n");
      out.write("	}\r\n");
      out.write("	]\r\n");
      out.write("});\r\n");
      out.write("chart.render();\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\"\r\n");
      out.write("	href=\"../plugins/images/favicon.png\">\r\n");
      out.write("<title>Pixel Admin</title>\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"");
      out.print(contextPath );
      out.write("/static/bootstrap/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- Menu CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"");
      out.print(contextPath );
      out.write("/static/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- toast CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"");
      out.print(contextPath );
      out.write("/static/plugins/bower_components/toast-master/css/jquery.toast.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- morris CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"");
      out.print(contextPath );
      out.write("/static/plugins/bower_components/morrisjs/morris.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- animation CSS -->\r\n");
      out.write("<link href=\"");
      out.print(contextPath );
      out.write("/static/css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"");
      out.print(contextPath );
      out.write("/static/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- color CSS -->\r\n");
      out.write("<link href=\"");
      out.print(contextPath );
      out.write("/static/css/colors/blue-dark.css\"\r\n");
      out.write("	id=\"theme\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/static/css/custom.css\">\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Preloader -->\r\n");
      out.write("	<div class=\"preloader\">\r\n");
      out.write("		<div class=\"cssload-speeding-wheel\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Page Content -->\r\n");
      out.write("	<div id=\"page-wrapper\">\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			<div class=\"row bg-title\">\r\n");
      out.write("				<div class=\"col-lg-3 col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("					<h4 class=\"page-title\">Dashboard</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- /.col-lg-12 -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- row -->\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<!--col -->\r\n");
      out.write("			<div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">\r\n");
      out.write("				<div class=\"white-box\">\r\n");
      out.write("					<div class=\"col-in row\">\r\n");
      out.write("						<div class=\"col-md-6 col-sm-6 col-xs-6\">\r\n");
      out.write("							<i data-icon=\"E\" class=\"linea-icon linea-basic\"></i>\r\n");
      out.write("							<h5 class=\"text-muted vb\">CHƯA BẮT ĐẦU</h5>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6 col-sm-6 col-xs-6\">\r\n");
      out.write("							<h3 class=\"counter text-right m-t-15 text-danger\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDto.notDoneWorkPercent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("							<div class=\"progress\">\r\n");
      out.write("								<div class=\"progress-bar progress-bar-danger\" role=\"progressbar\"\r\n");
      out.write("									aria-valuenow=\"40\" aria-valuemin=\"0\" aria-valuemax=\"100\"\r\n");
      out.write("									style=\"width: 40%\">\r\n");
      out.write("									<span class=\"sr-only\">40% Complete (success)</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- /.col -->\r\n");
      out.write("			<!--col -->\r\n");
      out.write("			<div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">\r\n");
      out.write("				<div class=\"white-box\">\r\n");
      out.write("					<div class=\"col-in row\">\r\n");
      out.write("						<div class=\"col-md-6 col-sm-6 col-xs-6\">\r\n");
      out.write("							<i class=\"linea-icon linea-basic\" data-icon=\"&#xe01b;\"></i>\r\n");
      out.write("							<h5 class=\"text-muted vb\">ĐANG THỰC HIỆN</h5>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6 col-sm-6 col-xs-6\">\r\n");
      out.write("							<h3 class=\"counter text-right m-t-15 text-megna\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDto.pendingWorkPercent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("							<div class=\"progress\">\r\n");
      out.write("								<div class=\"progress-bar progress-bar-megna\" role=\"progressbar\"\r\n");
      out.write("									aria-valuenow=\"40\" aria-valuemin=\"0\" aria-valuemax=\"100\"\r\n");
      out.write("									style=\"width: 40%\">\r\n");
      out.write("									<span class=\"sr-only\">40% Complete (success)</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- /.col -->\r\n");
      out.write("			<!--col -->\r\n");
      out.write("			<div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">\r\n");
      out.write("				<div class=\"white-box\">\r\n");
      out.write("					<div class=\"col-in row\">\r\n");
      out.write("						<div class=\"col-md-6 col-sm-6 col-xs-6\">\r\n");
      out.write("							<i class=\"linea-icon linea-basic\" data-icon=\"&#xe00b;\"></i>\r\n");
      out.write("							<h5 class=\"text-muted vb\">ĐÃ HOÀN THÀNH</h5>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6 col-sm-6 col-xs-6\">\r\n");
      out.write("							<h3 class=\"counter text-right m-t-15 text-primary\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDto.finishWorkPercent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("							<div class=\"progress\">\r\n");
      out.write("								<div class=\"progress-bar progress-bar-primary\"\r\n");
      out.write("									role=\"progressbar\" aria-valuenow=\"40\" aria-valuemin=\"0\"\r\n");
      out.write("									aria-valuemax=\"100\" style=\"width: 40%\">\r\n");
      out.write("									<span class=\"sr-only\">40% Complete (success)</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- /.col -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- /.row -->\r\n");
      out.write("		<!--row -->\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-12\">\r\n");
      out.write("				<div class=\"white-box\">\r\n");
      out.write("					<div id=\"chartContainer\" style=\"height: 370px; width: 100%;\"></div>\r\n");
      out.write("					<script src=\"https://canvasjs.com/assets/script/canvasjs.min.js\"> </script>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /.container-fluid -->\r\n");
      out.write("	<footer class=\"footer text-center\"> 2018 &copy; myclass.com </footer>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /#page-wrapper -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /#wrapper -->\r\n");
      out.write("	<!-- jQuery -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(contextPath );
      out.write("/static/plugins/bower_components/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("	<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(contextPath );
      out.write("/static/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!-- Menu Plugin JavaScript -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(contextPath );
      out.write("/static/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js\"></script>\r\n");
      out.write("	<!--slimscroll JavaScript -->\r\n");
      out.write("	<script src=\"");
      out.print(contextPath );
      out.write("/static/js/jquery.slimscroll.js\"></script>\r\n");
      out.write("	<!--Wave Effects -->\r\n");
      out.write("	<script src=\"");
      out.print(contextPath );
      out.write("/static/js/waves.js\"></script>\r\n");
      out.write("	<!--Counter js -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(contextPath );
      out.write("/static/plugins/bower_components/waypoints/lib/jquery.waypoints.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(contextPath );
      out.write("/static/plugins/bower_components/counterup/jquery.counterup.min.js\"></script>\r\n");
      out.write("	<!--Morris JavaScript -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(contextPath );
      out.write("/static/plugins/bower_components/raphael/raphael-min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(contextPath );
      out.write("/static/plugins/bower_components/morrisjs/morris.js\"></script>\r\n");
      out.write("	<!-- Custom Theme JavaScript -->\r\n");
      out.write("	<script src=\"");
      out.print(contextPath );
      out.write("/static/js/custom.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(contextPath );
      out.write("/static/js/dashboard1.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(contextPath );
      out.write("/static/plugins/bower_components/toast-master/js/jquery.toast.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
